[package]
name = "redis_example"
version = "0.1.0"
authors = ["woods <woods@mur>"]
edition = "2018"

[dependencies]
redis = "0.16.0"
tokio = { version = "0.2", features = ["full"] }
futures = "0.3.5"
crossbeam-channel = "0.4.2"
